# Generated by Django 5.1.5 on 2025-02-06 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_evento_alter_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='data_evento',
        ),
        migrations.AddField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='evento',
            name='horario_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
