# Generated by Django 5.1.5 on 2025-02-11 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_remove_evento_data_evento_evento_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horario_inicio',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
